var h,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},k="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,ba=function(){ba=function(){};k.Symbol||(k.Symbol=ca)},ca=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}(),ea=function(){ba();var a=k.Symbol.iterator;a||(a=k.Symbol.iterator=k.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&
aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return da(this)}});ea=function(){}},da=function(a){var b=0;return fa(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})},fa=function(a){ea();a={next:a};a[k.Symbol.iterator]=function(){return this};return a},ha=function(a){ea();var b=a[Symbol.iterator];return b?b.call(a):da(a)},ia=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);
if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},l=function(a,b){function c(){}c.prototype=b.prototype;
a.Pb=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Nb=function(a,c,g){for(var e=Array(arguments.length-2),d=2;d<arguments.length;d++)e[d-2]=arguments[d];return b.prototype[c].apply(a,e)}};var p=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,p);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};l(p,Error);p.prototype.name="CustomError";var ja=function(a,b){for(var c=a.split("%s"),d="",e=Array.prototype.slice.call(arguments,1);e.length&&1<c.length;)d+=c.shift()+e.shift();return d+c.join("%s")};var ka=function(a,b){b.unshift(a);p.call(this,ja.apply(null,b));b.shift()};l(ka,p);ka.prototype.name="AssertionError";var la=function(a,b,c){if(!a){var d="Assertion failed";if(b){d+=": "+b;var e=Array.prototype.slice.call(arguments,2)}throw new ka(""+d,e||[]);}};var ma=function(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);255<e&&(b[c++]=e&255,e>>=8);b[c++]=e}return b};var q=null;var na=function(){this.i=-1};var r=function(a,b,c){this.i=-1;this.w=a;this.i=c||a.i||16;this.Ja=Array(this.i);this.na=Array(this.i);a=b;a.length>this.i&&(this.w.update(a),a=this.w.digest(),this.w.reset());for(c=0;c<this.i;c++)b=c<a.length?a[c]:0,this.Ja[c]=b^92,this.na[c]=b^54;this.w.update(this.na)};l(r,na);r.prototype.reset=function(){this.w.reset();this.w.update(this.na)};r.prototype.update=function(a,b){this.w.update(a,b)};
r.prototype.digest=function(){var a=this.w.digest();this.w.reset();this.w.update(this.Ja);this.w.update(a);return this.w.digest()};var t=function(){this.i=64;this.h=Array(4);this.Za=Array(this.i);this.ba=this.S=0;this.reset()};l(t,na);t.prototype.reset=function(){this.h[0]=1732584193;this.h[1]=4023233417;this.h[2]=2562383102;this.h[3]=271733878;this.ba=this.S=0};
var oa=function(a,b,c){c||(c=0);var d=Array(16);if("string"==typeof b)for(var e=0;16>e;++e)d[e]=b.charCodeAt(c++)|b.charCodeAt(c++)<<8|b.charCodeAt(c++)<<16|b.charCodeAt(c++)<<24;else for(e=0;16>e;++e)d[e]=b[c++]|b[c++]<<8|b[c++]<<16|b[c++]<<24;b=a.h[0];c=a.h[1];e=a.h[2];var g=a.h[3];var f=b+(g^c&(e^g))+d[0]+3614090360&4294967295;b=c+(f<<7&4294967295|f>>>25);f=g+(e^b&(c^e))+d[1]+3905402710&4294967295;g=b+(f<<12&4294967295|f>>>20);f=e+(c^g&(b^c))+d[2]+606105819&4294967295;e=g+(f<<17&4294967295|f>>>
15);f=c+(b^e&(g^b))+d[3]+3250441966&4294967295;c=e+(f<<22&4294967295|f>>>10);f=b+(g^c&(e^g))+d[4]+4118548399&4294967295;b=c+(f<<7&4294967295|f>>>25);f=g+(e^b&(c^e))+d[5]+1200080426&4294967295;g=b+(f<<12&4294967295|f>>>20);f=e+(c^g&(b^c))+d[6]+2821735955&4294967295;e=g+(f<<17&4294967295|f>>>15);f=c+(b^e&(g^b))+d[7]+4249261313&4294967295;c=e+(f<<22&4294967295|f>>>10);f=b+(g^c&(e^g))+d[8]+1770035416&4294967295;b=c+(f<<7&4294967295|f>>>25);f=g+(e^b&(c^e))+d[9]+2336552879&4294967295;g=b+(f<<12&4294967295|
f>>>20);f=e+(c^g&(b^c))+d[10]+4294925233&4294967295;e=g+(f<<17&4294967295|f>>>15);f=c+(b^e&(g^b))+d[11]+2304563134&4294967295;c=e+(f<<22&4294967295|f>>>10);f=b+(g^c&(e^g))+d[12]+1804603682&4294967295;b=c+(f<<7&4294967295|f>>>25);f=g+(e^b&(c^e))+d[13]+4254626195&4294967295;g=b+(f<<12&4294967295|f>>>20);f=e+(c^g&(b^c))+d[14]+2792965006&4294967295;e=g+(f<<17&4294967295|f>>>15);f=c+(b^e&(g^b))+d[15]+1236535329&4294967295;c=e+(f<<22&4294967295|f>>>10);f=b+(e^g&(c^e))+d[1]+4129170786&4294967295;b=c+(f<<
5&4294967295|f>>>27);f=g+(c^e&(b^c))+d[6]+3225465664&4294967295;g=b+(f<<9&4294967295|f>>>23);f=e+(b^c&(g^b))+d[11]+643717713&4294967295;e=g+(f<<14&4294967295|f>>>18);f=c+(g^b&(e^g))+d[0]+3921069994&4294967295;c=e+(f<<20&4294967295|f>>>12);f=b+(e^g&(c^e))+d[5]+3593408605&4294967295;b=c+(f<<5&4294967295|f>>>27);f=g+(c^e&(b^c))+d[10]+38016083&4294967295;g=b+(f<<9&4294967295|f>>>23);f=e+(b^c&(g^b))+d[15]+3634488961&4294967295;e=g+(f<<14&4294967295|f>>>18);f=c+(g^b&(e^g))+d[4]+3889429448&4294967295;c=
e+(f<<20&4294967295|f>>>12);f=b+(e^g&(c^e))+d[9]+568446438&4294967295;b=c+(f<<5&4294967295|f>>>27);f=g+(c^e&(b^c))+d[14]+3275163606&4294967295;g=b+(f<<9&4294967295|f>>>23);f=e+(b^c&(g^b))+d[3]+4107603335&4294967295;e=g+(f<<14&4294967295|f>>>18);f=c+(g^b&(e^g))+d[8]+1163531501&4294967295;c=e+(f<<20&4294967295|f>>>12);f=b+(e^g&(c^e))+d[13]+2850285829&4294967295;b=c+(f<<5&4294967295|f>>>27);f=g+(c^e&(b^c))+d[2]+4243563512&4294967295;g=b+(f<<9&4294967295|f>>>23);f=e+(b^c&(g^b))+d[7]+1735328473&4294967295;
e=g+(f<<14&4294967295|f>>>18);f=c+(g^b&(e^g))+d[12]+2368359562&4294967295;c=e+(f<<20&4294967295|f>>>12);f=b+(c^e^g)+d[5]+4294588738&4294967295;b=c+(f<<4&4294967295|f>>>28);f=g+(b^c^e)+d[8]+2272392833&4294967295;g=b+(f<<11&4294967295|f>>>21);f=e+(g^b^c)+d[11]+1839030562&4294967295;e=g+(f<<16&4294967295|f>>>16);f=c+(e^g^b)+d[14]+4259657740&4294967295;c=e+(f<<23&4294967295|f>>>9);f=b+(c^e^g)+d[1]+2763975236&4294967295;b=c+(f<<4&4294967295|f>>>28);f=g+(b^c^e)+d[4]+1272893353&4294967295;g=b+(f<<11&4294967295|
f>>>21);f=e+(g^b^c)+d[7]+4139469664&4294967295;e=g+(f<<16&4294967295|f>>>16);f=c+(e^g^b)+d[10]+3200236656&4294967295;c=e+(f<<23&4294967295|f>>>9);f=b+(c^e^g)+d[13]+681279174&4294967295;b=c+(f<<4&4294967295|f>>>28);f=g+(b^c^e)+d[0]+3936430074&4294967295;g=b+(f<<11&4294967295|f>>>21);f=e+(g^b^c)+d[3]+3572445317&4294967295;e=g+(f<<16&4294967295|f>>>16);f=c+(e^g^b)+d[6]+76029189&4294967295;c=e+(f<<23&4294967295|f>>>9);f=b+(c^e^g)+d[9]+3654602809&4294967295;b=c+(f<<4&4294967295|f>>>28);f=g+(b^c^e)+d[12]+
3873151461&4294967295;g=b+(f<<11&4294967295|f>>>21);f=e+(g^b^c)+d[15]+530742520&4294967295;e=g+(f<<16&4294967295|f>>>16);f=c+(e^g^b)+d[2]+3299628645&4294967295;c=e+(f<<23&4294967295|f>>>9);f=b+(e^(c|~g))+d[0]+4096336452&4294967295;b=c+(f<<6&4294967295|f>>>26);f=g+(c^(b|~e))+d[7]+1126891415&4294967295;g=b+(f<<10&4294967295|f>>>22);f=e+(b^(g|~c))+d[14]+2878612391&4294967295;e=g+(f<<15&4294967295|f>>>17);f=c+(g^(e|~b))+d[5]+4237533241&4294967295;c=e+(f<<21&4294967295|f>>>11);f=b+(e^(c|~g))+d[12]+1700485571&
4294967295;b=c+(f<<6&4294967295|f>>>26);f=g+(c^(b|~e))+d[3]+2399980690&4294967295;g=b+(f<<10&4294967295|f>>>22);f=e+(b^(g|~c))+d[10]+4293915773&4294967295;e=g+(f<<15&4294967295|f>>>17);f=c+(g^(e|~b))+d[1]+2240044497&4294967295;c=e+(f<<21&4294967295|f>>>11);f=b+(e^(c|~g))+d[8]+1873313359&4294967295;b=c+(f<<6&4294967295|f>>>26);f=g+(c^(b|~e))+d[15]+4264355552&4294967295;g=b+(f<<10&4294967295|f>>>22);f=e+(b^(g|~c))+d[6]+2734768916&4294967295;e=g+(f<<15&4294967295|f>>>17);f=c+(g^(e|~b))+d[13]+1309151649&
4294967295;c=e+(f<<21&4294967295|f>>>11);f=b+(e^(c|~g))+d[4]+4149444226&4294967295;b=c+(f<<6&4294967295|f>>>26);f=g+(c^(b|~e))+d[11]+3174756917&4294967295;g=b+(f<<10&4294967295|f>>>22);f=e+(b^(g|~c))+d[2]+718787259&4294967295;e=g+(f<<15&4294967295|f>>>17);f=c+(g^(e|~b))+d[9]+3951481745&4294967295;a.h[0]=a.h[0]+b&4294967295;a.h[1]=a.h[1]+(e+(f<<21&4294967295|f>>>11))&4294967295;a.h[2]=a.h[2]+e&4294967295;a.h[3]=a.h[3]+g&4294967295};
t.prototype.update=function(a,b){void 0===b&&(b=a.length);for(var c=b-this.i,d=this.Za,e=this.S,g=0;g<b;){if(0==e)for(;g<=c;)oa(this,a,g),g+=this.i;if("string"==typeof a)for(;g<b;){if(d[e++]=a.charCodeAt(g++),e==this.i){oa(this,d);e=0;break}}else for(;g<b;)if(d[e++]=a[g++],e==this.i){oa(this,d);e=0;break}}this.S=e;this.ba+=b};
t.prototype.digest=function(){var a=Array((56>this.S?this.i:2*this.i)-this.S);a[0]=128;for(var b=1;b<a.length-8;++b)a[b]=0;var c=8*this.ba;for(b=a.length-8;b<a.length;++b)a[b]=c&255,c/=256;this.update(a);a=Array(16);for(b=c=0;4>b;++b)for(var d=0;32>d;d+=8)a[c++]=this.h[b]>>>d&255;return a};var u={Mb:{}},w,pa=!1,x=function(a){try{pa&&window.console&&window.console.log&&window.console.log(a)}catch(b){}},y=function(a,b){if(!a)return-1;if(a.indexOf)return a.indexOf(b,void 0);for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1},z=function(a,b){function c(){}if(!a)throw"Child class cannot be empty.";if(!b)throw"Parent class cannot be empty.";c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a},qa=function(a){return"[object Function]"===Object.prototype.toString.call(a)},
ra=function(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];if(null===d||void 0===d)d="";b.push(encodeURIComponent(c)+"="+encodeURIComponent(d))}return b.join("&")},sa=function(a){a=(new RegExp("[&#]"+a+"=([^&]*)")).exec(window.location.hash);return null==a?"":decodeURIComponent(a[1].replace(/\+/g," "))},ta=function(a,b,c){if(a.addEventListener)a.addEventListener(b,c,!1);else if(a.attachEvent)a.attachEvent("on"+b,c);else throw"Add event handler for "+b+" failed.";},A=function(a,b){a=(a||
"").split(" ");b=(b||"").split(" ");for(var c=0;c<b.length;c++)if(b[c]&&0>y(a,b[c]))return!1;return!0},ua=function(){if("undefined"!=typeof w)return w;var a=window.localStorage?window.localStorage:void 0;if(!a)return w=!1;try{a.setItem("test","test"),a.removeItem("test"),w=!0}catch(b){w=!1}return w},va=function(){var a=navigator.userAgent.toLowerCase();return-1!=a.indexOf("msie")&&8==parseInt(a.split("msie")[1],10)},B=function(){return Object.hasOwnProperty.call(window,"ActiveXObject")&&!window.ActiveXObject},
wa=function(){var a=navigator.userAgent;return!!a&&/Edge\/\d+/.test(a)},xa=function(){var a=navigator.userAgent,b;if(b=!!a&&-1!=a.indexOf("CriOS"))b=-1,(a=a.match(/CriOS\/(\d+)/))&&a[1]&&(b=parseInt(a[1],10)||-1),b=48>b;return b},ya=function(){var a=navigator.userAgent.toLowerCase();return-1<a.indexOf("safari/")&&0>a.indexOf("chrome/")&&0>a.indexOf("crios/")&&0>a.indexOf("android")},C=function(a){this.sa=a||[];this.A={}};
C.prototype.addEventListener=function(a,b){if(!(0<=y(this.sa,a)))throw"Unrecognized event type: "+a;if(!qa(b))throw"The listener for event '"+a+"' is not a function.";this.A[a]||(this.A[a]=[]);0>y(this.A[a],b)&&this.A[a].push(b)};C.prototype.removeEventListener=function(a,b){if(!(0<=y(this.sa,a)))throw"Unrecognized event type: "+a;qa(b)&&this.A[a]&&this.A[a].length&&(b=y(this.A[a],b),0<=b&&this.A[a].splice(b,1))};
C.prototype.dispatchEvent=function(a){var b=a.type;if(!(b&&0<=y(this.sa,b)))throw"Failed to dispatch unrecognized event type: "+b;if(this.A[b]&&this.A[b].length)for(var c=0,d=this.A[b].length;c<d;c++)this.A[b][c](a)};var D=D||{};D.J=function(a){a=encodeURIComponent(a);var b=D.Ea();if(b&&(a=b.match("(^|;) ?"+a+"=([^;]*)(;|$)"))&&2<a.length&&(a=a[2]))return decodeURIComponent(a)};D.jb=function(a){var b;(a=D.J(a))&&(b=String(za(a)));return b};D.Ea=function(){return document.cookie};
D.Gb=function(a){document.cookie=a};u=u||{};
u.rb=function(a,b){if(!0===u.ka)a();else{var c=2,d=function(){c--;0==c&&(u.ka=!0,a())},e=function(a){b(a)};switch(Aa()){case "sessionStorage":u.aa=new Ba;u.aa.H(d,e);break;case "inMemoryStorage":u.aa=new Ca;u.aa.H(d,e);break;default:d=Error("Unsupported storage type: "+Aa());b(d);return}switch(Da()){case "localStorage":u.N=new Ea;u.N.H(d,e);break;case "indexedDb":u.N=new Fa;u.N.H(d,e);break;case "cookieStorage":u.N=new Ga;u.N.H(d,e);break;default:d=Error("Unsupported storage type: "+Da()),b(d)}}};
u.Ga=function(){if(!u.ka)throw Error("Storages are not initialized yet!");return u.N};u.pb=function(){if(!u.ka)throw Error("Storages are not initialized yet!");return u.aa};var Ea=function(){};h=Ea.prototype;h.H=function(a,b){ua()?(this.T=window.localStorage,a()):b&&b(Error("localStorage is not available in the current environment."))};h.getItem=function(a,b){b(this.T.getItem(a))};h.setItem=function(a,b,c){void 0===b||null===b?this.T.removeItem(a):this.T.setItem(a,b);c&&c()};
h.removeItem=function(a,b){this.T.removeItem(a);b&&b()};h.clear=function(a){this.T.clear();a&&a()};var Fa=function(){};h=Fa.prototype;h.H=function(a,b){var c=this,d=window.indexedDB.open("oauth");d.onsuccess=function(b){c.Y=b.target.result;a()};d.onupgradeneeded=function(a){a.target.result.createObjectStore("oauth")};d.onerror=function(a){a=a.target.errorCode;b&&b(Error("IndexedDb initialization failed: "+a))}};
h.getItem=function(a,b){var c=this.Y.transaction("oauth","readwrite").objectStore("oauth").get(a);c.onsuccess=function(){b(c.result)}};h.setItem=function(a,b,c){var d=this.Y.transaction("oauth","readwrite").objectStore("oauth");if(void 0===b||null===b)d["delete"](a);else d.put(b,a);d.transaction.oncomplete=function(){c&&c()}};h.removeItem=function(a,b){var c=this.Y.transaction("oauth","readwrite").objectStore("oauth");c["delete"](a);c.transaction.oncomplete=function(){b&&b()}};
h.clear=function(a){var b=this.Y.transaction("oauth","readwrite").objectStore("oauth");b.clear();b.transaction.oncomplete=function(){a&&a()}};var Ca=function(){};h=Ca.prototype;h.H=function(a){this.$={};a()};h.getItem=function(a,b){b(this.$[a]||null)};h.setItem=function(a,b,c){this.$[a]=b;c&&c()};h.removeItem=function(a,b){delete this.$[a];b&&b()};h.clear=function(a){this.$={};a&&a()};var Ba=function(){};h=Ba.prototype;h.H=function(a,b){ua()?(this.X=window.sessionStorage,a()):b&&b(Error("sessionStorage is not available in the current environment."))};
h.getItem=function(a,b){b(this.X.getItem(a))};h.setItem=function(a,b,c){void 0===b||null===b?this.X.removeItem(a):this.X.setItem(a,b);c&&c()};h.removeItem=function(a,b){this.X.removeItem(a);b&&b()};h.clear=function(a){this.X.clear();a&&a()};var Ga=function(){this.vb=E.Qa};h=Ga.prototype;h.H=function(a,b){navigator.cookieEnabled?a():b&&b(Error("Cookies are not enabled in current environment."))};h.getItem=function(a,b){for(var c=null,d=Ha(a),e=0;e<d.length;e++)if(d[e].key==a){c=d[e].value;break}b(c)};
h.setItem=function(a,b,c){var d=E.ha(a.split(E.g)[0]);if(d){var e=Ia(d);b={key:a,value:b};for(var g=0;g<e.length;g++)if(e[g].key==a){e.splice(g,1);break}e.push(b);Ja(this,d,e)}c&&c()};h.removeItem=function(a,b){for(var c=Ha(a),d=0;d<c.length;d++)if(c[d].key==a){c.splice(d,1);break}(a=E.ha(a.split(E.g)[0]))&&Ja(this,a,c);b&&b()};h.clear=function(a){u.$a();a&&a()};
var Ha=function(a){return(a=E.ha(a.split(E.g)[0]))?Ia(a):[]},Ia=function(a){a=D.J(a);return u.bb(a||null)},Ja=function(a,b,c){var d=u.eb(c);d.length>a.vb?(c.splice(0,1),0<c.length?Ja(a,b,c):x("Failed to write Cookie based cache due to the big size.")):u.Na(b,d)};u.ab=function(a){try{return atob(a)}catch(b){return a}};u.cb=function(a){try{return btoa(a)}catch(b){return a}};
u.bb=function(a){if(!a)return[];a=u.ab(a);try{return JSON.parse(a).items||[]}catch(b){return x("Error while parsing items from cookie:"+b.message),[]}};u.eb=function(a){return u.cb(JSON.stringify({items:a}))};u.Na=function(a,b){var c=window.location.hostname,d=window.location.pathname;a=encodeURIComponent(a)+"="+encodeURIComponent(b)+"; domain="+c+";";-1!=navigator.userAgent.toLowerCase().indexOf("msie")||B()||(a+=" path="+d+";");"https:"==window.location.protocol&&(a+=" secure;");D.Gb(a)};
u.$a=function(){var a=E.da,b=D.Ea();if(b){b=b.replace(/((?:^|\s*;)[^\=]+)(?=;|$)|^\s*|\s*(?:\=[^;]*)?(?:\1|$)/g,"").split(/\s*(?:\=[^;]*)?;\s*/);for(var c=0;c<b.length;c++){var d=decodeURIComponent(b[c]);0==d.indexOf(a)&&u.Na(d,"")}}};var F=function(a){this.Ka=a;C.call(this,["storageValueChanged"])};z(F,C);var Ka=function(a,b){u.Ga().getItem(a.Ka,b)};F.prototype.addListener=function(a){this.addEventListener("storageValueChanged",a)};
F.prototype.start=function(){var a=this;Ka(this,function(b){a.zb=b;a.La=0;a.la=window.setInterval(La(a),200)})};F.prototype.stop=function(){void 0!==this.la&&(clearInterval(this.la),this.la=void 0)};
var La=function(a){return function(){a.La++;Ka(a,function(b){b!=a.zb?(a.dispatchEvent({type:"storageValueChanged",key:a.Ka,newValue:b}),a.stop()):1500<=a.La&&a.stop()})}},za=function(a){var b=0,c;if(a){var d=0;for(c=a.length;d<c;d++){var e=a.charCodeAt(d);b=(b<<5)-b+e;b|=0}}return b},G=function(a){return!!a&&0<=a.indexOf(E.g)},Ma=function(a,b){if(!a&&!b)return!0;if(!a||!b)return!1;a=a.extraQueryParams;b=b.extraQueryParams;if(!a&&!b)return!0;if(!a||!b||Object.keys&&Object.keys(a).length!=Object.keys(b).length)return!1;
for(var c in a)if(a[c]!==b[c])return!1;if(!Object.keys)for(c in b)if(a[c]!==b[c])return!1;return!0},E=E||{};E.ga="SID";E.ya="SSID";E.Pa=100;E.Aa="/oauth2/sessionstate/action/updateState";E.ta="/oauth2/sessionstate/action/checkOrigin";E.xa="/oauth2/permission/action/refresh";E.wa="/oauth2/permission/action/code";E.fa="/oauth2/permission/action/listSessions";E.Wa="/o/oauth2/revoke";E.Ta="response_type login_hint client_id origin scope ss_domain authuser hd include_granted_scopes".split(" ");E.Sa="login_hint client_id origin scope ss_domain authuser hd include_granted_scopes".split(" ");
E.Ua=["client_id","origin","scope","ss_domain","authuser"];E.g="::";E.ea="_ss_";E.va="_tr_";E.R="oauth2_ss";E.ua="oauth2_cs";E.za="oauth2_tr";E.Ra="oauth2_is";E.P="oauth2_ar";E.da="oauth2c_";E.Qa=1500;E.Lb=function(){var a={ea:1,va:2,R:3,ua:4,za:5,P:6},b;for(b in a)if(a=E[b],!a||0<=a.indexOf(E.g))throw"Invalid value for 'oauth2.spi."+b+"'.";};E.Lb();E.Va=512;
E.Xa=function(a){var b;(b=void 0===a.hint)||(b=a.hint,b=(""===b?!0:b?"string"==typeof b||"object"==typeof b&&b.constructor===String:!1)&&a.hint.length<=E.Va);return!a.id&&b};E.nb=function(){return"https:"==window.location.protocol?E.ya:E.ga};E.ha=function(a){switch(a){case E.P:return E.da+E.P;case E.R:return E.da+E.R;default:return null}};
var Da=function(){return ya()&&!ua()||B()&&!window.indexedDB?"cookieStorage":B()||wa()?"indexedDb":"localStorage"},Aa=function(){return ya()&&!ua()?"inMemoryStorage":"sessionStorage"};D=D||{};D.ca="cookieValueChanged";var Na=function(a,b){this.Ca=a;this.sb=b;C.call(this,[D.ca])};z(Na,C);Na.prototype.J=function(){return D.J(this.Ca)};var H=function(a){return D.jb(a.Ca)};Na.prototype.addListener=function(a){this.addEventListener(D.ca,a)};
var Qa=function(a){Oa(a);a.Z=a.J();a.qa=window.setInterval(Pa(a),a.sb);x("IDP Session Cookie monitor is started.")},Oa=function(a){void 0!==a.qa&&(window.clearInterval(a.qa),a.qa=void 0,x("IDP Session Cookie monitor is stoped."))},Pa=function(a){return function(){var b=a.J();if(a.Z!=b){var c={type:D.ca,newHash:b&&za(b),oldHash:a.Z&&za(a.Z)};a.Z=b;a.dispatchEvent(c)}}},Ra=function(a,b){this.b=a;this.Oa=b},Sa=function(a,b,c){var d=E.Wa,e=new XMLHttpRequest;e.onreadystatechange=function(){if(4==e.readyState&&
200==e.status){var a;e.responseText&&(a=window.JSON.parse(e.responseText));c(a)}};e.open("POST",d,!0);e.setRequestHeader("Content-type","application/x-www-form-urlencoded");var g="xsrfToken=";a.Oa&&(g+=a.Oa);if(b)for(var f in b)f&&b[f]&&(g+="&"+f+"="+encodeURIComponent(b[f]));x("Call "+d+" with postData: "+g);e.send(g)},I=function(a,b,c,d){var e=new XMLHttpRequest;e.onreadystatechange=function(){if(4==e.readyState&&200==e.status){var a;e.responseText&&(a=window.JSON.parse(e.responseText));d(a)}};
if(b=ra(b))a+=0>a.indexOf("?")?"?":"&",a+=b;e.open("GET",a,!0);if(c)for(var g in c)if(c.hasOwnProperty(g)){b=c[g];if(null===b||void 0===b)b="";e.setRequestHeader(g,b)}x("Call "+a+" with Get method.");e.send()},Ta=function(a,b,c){I(E.ta,{origin:a.b,client_id:b},null,c)},Ua=function(a,b,c){b&&b.length?I(E.Aa,{login_hint:b.join(" "),origin:a.b},null,c):c({activeHints:{}})},Wa=function(a,b,c){b.origin=a.b;b=Va(b,E.Ta);I(E.xa,b,null,c)},Xa=function(a,b,c){b.origin=a.b;b=Va(b,E.Sa);I(E.wa,b,null,c)},Ya=
function(a,b,c){b.origin=a.b;b=Va(b,E.Ua);I(E.fa,b,null,c)},Za=function(a,b,c){Sa(a,{token:b},c)},Va=function(a,b){for(var c={},d=0;d<b.length;d++){var e=b[d];null!=a[e]&&(c[e]=a[e])}return c};u=u||{};var $a=function(){};$a.prototype.s=function(){return!1};var ab={};u.Bb=function(){var a=new J;if(!a)throw"policy cannot be empty.";if(u.Ia("DEFAULT"))throw"Duplicate policyName [DEFAULT].";ab.DEFAULT=a};u.Ia=function(a){for(var b in ab)if(a==b)return!0;return!1};
u.Fa=function(a){return a&&u.Ia(a)?a:"DEFAULT"};u.kb=function(a){return ab[u.Fa(a)]};u.s=function(a,b,c,d){return u.kb(d).s(a,b,c)};u.Ob=function(a,b,c,d){if(!u.s(a,b,c,d))throw"permission_error";};var bb=function(){};z(bb,$a);bb.prototype.s=function(a,b,c){a=c?this.ia(a):this.ja(a);return 0<=y(a,b)};
bb.prototype.ja=function(a){var b=[];if(a&&(b.push(a),"http://"==a.substring(0,7)||"https://"==a.substring(0,8))){var c=document.createElement("a");c.href=a;a!=c.protocol+"//"+c.hostname&&b.push(c.protocol+"//"+c.hostname);"https:"==c.protocol&&b.push("http://"+c.hostname)}return b};
bb.prototype.ia=function(a){var b=[];if(a){b.push(a);var c=document.createElement("a");c.href=a;if("http:"==c.protocol||"https:"==c.protocol)for(a=c.hostname.split(".");1<a.length;)b.push(c.protocol+"//"+a.join(".")),"https:"==c.protocol&&b.push("http://"+a.join(".")),a.shift()}return b};var J=function(){};z(J,$a);J.prototype.s=function(a,b,c){a=c?this.ia(a):this.ja(a);return 0<=y(a,b)};
J.prototype.ja=function(a){var b=[];if(a&&(b.push(a),"https://"==a.substring(0,8))){var c=document.createElement("a");c.href=a;""!=c.port&&0!=c.port&&443!=c.port||b.push("http://"+c.hostname)}return b};
J.prototype.ia=function(a){var b=[];if(a){var c=document.createElement("a");c.href=a;if("https:"==c.protocol&&(""==c.port||0==c.port||443==c.port)||"http:"==c.protocol&&(""==c.port||0==c.port||80==c.port))for(a=c.hostname.split(".");1<a.length;)b.push(c.protocol+"//"+a.join(".")),"https:"==c.protocol&&b.push("http://"+a.join(".")),a.shift();else b.push(a)}return b};u.Bb();var K=function(){};K.prototype.ma=function(){return!0};var L=function(a){return a.ma()?u.pb():u.Ga()};
K.prototype.f=function(){throw Error("unimplemented abstract method");};K.prototype.M=function(){throw Error("unimplemented abstract method");};K.prototype.l=function(){throw Error("unimplemented abstract method");};K.prototype.m=function(){throw Error("unimplemented abstract method");};var M=function(){};z(M,K);
M.prototype.l=function(a,b,c){var d=this,e=this.f(a);L(this).getItem(e,function(a){if(a)try{var f=window.JSON.parse(a);if(f.cookieHash!=b){L(d).removeItem(e,function(){c(void 0)});return}var g=f&&f.cachedValue}catch(m){}c(g)})};M.prototype.m=function(a,b,c,d){a=this.f(a);void 0===b||null===b?L(this).removeItem(a,d):(b=JSON.stringify({cookieHash:c,cachedValue:b}),L(this).setItem(a,b,d))};var N=function(){};z(N,K);
N.prototype.l=function(a,b,c){L(this).getItem(this.f(a),function(a){if(a)try{var b=window.JSON.parse(a);var d=b&&b.cachedValue}catch(f){}c(d)})};N.prototype.m=function(a,b,c,d){a=this.f(a);void 0===b||null===b?L(this).removeItem(a,d):(b=JSON.stringify({cachedValue:b}),L(this).setItem(a,b,d))};var O=function(){};z(O,N);O.prototype.ma=function(){return!1};O.prototype.f=function(a){return[E.P,a.origin,a.clientId,a.id].join(E.g)};
O.prototype.M=function(a){var b={};a&&(a=a.split(E.g),4==a.length&&(b.origin=a[1],b.clientId=a[2],b.id=a[3]));return b};var cb=function(){};z(cb,M);cb.prototype.f=function(a){return[E.ua,a.origin,a.clientId].join(E.g)};cb.prototype.M=function(a){a=a.split(E.g);var b={};3==a.length&&(b.origin=a[1],b.clientId=a[2]);return b};var P=function(){};z(P,M);P.prototype.f=function(a){return[E.Ra,a.origin,a.clientId].join(E.g)};
P.prototype.l=function(a,b,c){var d=this;M.prototype.l.call(this,a,b,function(b){b&&b.expires_at?6E4>b.expires_at-(new Date).getTime()?L(d).removeItem(d.f(a),c):A(b.scope,a.scope)&&A(a.scope,b.scope)?(b.expires_in=Math.floor((b.expires_at-(new Date).getTime())/1E3),c&&c(b)):L(d).removeItem(d.f(a),c):c&&c(void 0)})};P.prototype.m=function(a,b,c,d){var e;b&&b.expires_at&&18E4<b.expires_at-(new Date).getTime()&&(e=b);M.prototype.m.call(this,a,e,c,d)};var Q=function(){};z(Q,N);Q.prototype.ma=function(){return!1};
Q.prototype.f=function(a){return[E.R,a.domain,a.crossSubDomains?"1":"0",u.Fa(a.policy),a.id||E.ea].join(E.g)};Q.prototype.M=function(a){a=a.split(E.g);var b={};5==a.length&&(b.domain=a[1],b.crossSubDomains="1"==a[2],b.policy=a[3],b.id=a[4]);"DEFAULT"==b.policy&&delete b.policy;b.id==E.ea&&delete b.id;return b};var R=function(a){this.yb=a||E.za};z(R,M);R.prototype.f=function(a){return[this.yb,a.origin,a.clientId,a.id||E.va].join(E.g)};
R.prototype.l=function(a,b,c){var d=this;M.prototype.l.call(this,a,b,function(b){b&&b.O&&b.O.expires_at?a.loginHint!=b.O.login_hint?L(d).removeItem(d.f(a),c):6E4>b.O.expires_at-(new Date).getTime()?L(d).removeItem(d.f(a),c):A(b.O.scope,a.scope)?A(b.responseType,a.responseType)?(b=b.O,b.expires_in=Math.floor((b.expires_at-(new Date).getTime())/1E3),c&&c(b)):L(d).removeItem(d.f(a),c):L(d).removeItem(d.f(a),c):c&&c(void 0)})};
R.prototype.m=function(a,b,c,d){var e;b&&b.expires_at&&18E4<b.expires_at-(new Date).getTime()&&(e={O:b,responseType:a.responseType});M.prototype.m.call(this,a,e,c,d)};var db=function(a,b){this.b=a;this.oa=b;this.W={};this.V={}},eb=function(a,b){if(!b)throw"message object cannot be null.";b.rpcToken=a.oa;b=JSON.stringify(b);x("IDP IFrame sends message: "+b);window.parent.postMessage(b,a.b)},S=function(a,b,c){b&&eb(a,{id:b,result:c})};
db.prototype.Ab=function(a){if(a.source==window.parent&&a.origin==this.b){x("IDP Session State IFrame receive message:"+a.data);try{var b=window.JSON.parse(a.data)}catch(c){return}(b.rpcToken||this.oa)&&b.rpcToken!=this.oa?x("RPC token mismatch."):b&&b.method&&this.W[b.method]?(a=this.W[b.method],a.I&&!b.id?x("Bad request."):a.B&&!a.B(b)?(x("Bad request."),eb(this,{id:b.id,error:"bad_request"})):a.v(b)):x("Bad request.")}};
var T=function(a,b){if(b&&b.type&&a.V[b.type]){var c=a.V[b.type].filter;c&&!c(b)||eb(a,{method:"fireIdpEvent",params:b})}else x("Invalid event type.")},fb=function(a,b){a.W={};a.V={};if(b){if(b.u)for(var c=0;c<b.u.length;c++){var d=b.u[c];if(!d.method||!d.v)throw"Error in RPC policy: method or handler is empty.";if(a.W[d.method])throw"Error in RPC policy: duplicate entry for RPC '"+d.method+"'.";var e=d.method;a.W[e]={v:d.v,I:d.I,B:d.B,method:e}}if(b.G)for(c=0;c<b.G.length;c++){d=b.G[c];if(!d.type)throw"Error in Event policy: type is empty.";
if(a.V[d.type])throw"Error in Event policy: duplicate entry for type '"+d.type+"'.";e=d.type;a.V[e]={filter:d.filter,type:e}}}},gb=function(a,b,c,d){T(a,{type:"sessionStateChanged",clientId:b,user:c,sessionState:d})},hb=function(a){var b=new Q,c=E.R+E.g;return function(d){if(d.key&&0===d.key.indexOf(c)){var e=b.M(d.key);if(u.s(a.b,e.domain,e.crossSubDomains,e.policy)){var g;if(d.newValue)try{var f=JSON.parse(d.newValue);f&&(g=f.cachedValue)}catch(n){return}T(a,{type:"sessionSelectorChanged",newValue:g,
crossSubDomains:e.crossSubDomains,domain:e.domain,policy:e.policy,id:e.id})}}}},ib=function(a){var b=new O,c=[E.P,a.b].join(E.g)+E.g;return function(d){if(!d.key&&va()){var e=null,g=[];for(d=0;d<window.localStorage.length;d++){var f=window.localStorage.key(d);if(0===f.indexOf(c))if(e)g.push(f);else{var n=window.localStorage.getItem(f);g.push(f);if(n){try{var m=window.JSON.parse(n)}catch(v){continue}m&&m.cachedValue&&(e=b.M(f),e={type:"authResult",clientId:e.clientId,id:e.id,authResult:m.cachedValue})}}}for(d=
0;d<g.length;d++)window.localStorage.removeItem(g[d]);(m=e)&&T(a,m)}else if(d.key&&0===d.key.indexOf(c)&&d.newValue){try{g=window.JSON.parse(d.newValue)}catch(v){return}g&&g.cachedValue&&(m=b.M(d.key),m={type:"authResult",clientId:m.clientId,id:m.id,authResult:g.cachedValue},T(a,m))}}},jb=function(a,b){this.b=a;this.j=b;this.Ba=new cb;this.Ma=new Q;this.ra=new R;this.Ha=new P},kb=function(a,b,c,d,e){a.Ba.m({origin:a.b,clientId:b},{user:c.D,session:c.D?c.K:void 0},d,e)},lb=function(a,b,c){a.Ba.l({origin:a.b,
clientId:b},H(a.j),c)},mb=function(a,b,c,d,e,g,f){a.ra.l({loginHint:b,origin:a.b,clientId:c,responseType:d,scope:e,id:g},H(a.j),f)},nb=function(a,b,c,d,e,g,f){a.ra.m({origin:a.b,clientId:c,responseType:d,id:g},e,b,f)},ob=function(a,b,c){var d=a.ra;a={origin:a.b,clientId:b};L(d).removeItem(d.f(a),c)},pb=function(a,b,c,d,e,g){if(!a.s(b,c,e))throw"Permission denied for '"+a.b+"' to read session selector for domain '"+b+"'.";a.Ma.l({domain:b,crossSubDomains:c,policy:e,id:d},void 0,function(a){g&&g(a)})},
qb=function(a,b,c,d,e,g,f){if(!a.s(b,c,g))throw"Permission denied for '"+a.b+"' to write session selector for domain '"+b+"'.";a.Ma.m({domain:b,crossSubDomains:c,policy:g,id:e},d,void 0,f)};jb.prototype.s=function(a,b,c){return u.s(this.b,a,b,c)};
var rb=function(a,b,c,d){a.Ha.l({origin:a.b,clientId:b,scope:c},H(a.j),d)},sb=function(a,b,c,d,e){a.Ha.m({origin:a.b,clientId:c},d,b,e)},tb=function(a,b,c){this.L=a;this.a=b;this.c=c},ub=function(a,b,c){a.D?c&&void 0!==c[a.D]?(c=c[a.D],Ma(a.K,c)||(a.K=c,kb(a.c,a.L,a,b,function(){gb(a.a,a.L,a.D,a.K)}))):a.K&&(a.K=void 0,kb(a.c,a.L,a,b,function(){gb(a.a,a.L,a.D,void 0)})):b&&gb(a.a,a.L,a.D,void 0)},wb=function(a,b,c,d){this.j=a;this.a=b;this.C=c;this.c=d;this.U=void 0;this.o={};this.pa=[];var e=this;
this.j.addListener(function(a){vb(e,a)})},xb=function(a){var b=[],c;for(c in a.o){var d=a.o[c].D;d&&b.push(d)}return b},vb=function(a,b){if(b.newHash)Ua(a.C,xb(a),function(c){for(var d in a.o)ub(a.o[d],b.newHash,c&&c.activeHints)});else for(var c in a.o)ub(a.o[c],b.newHash,void 0)},yb=function(a,b,c,d,e){var g=a.o[b];g||(g=new tb(b,a.a,a.c),a.o[b]=g);a=g;b=c.login_hint;c=c.session_state;a.D!=b?(a.D=b,a.K=b?c:void 0,kb(a.c,a.L,a,d,e)):e&&e()},zb=function(a,b,c){var d=a.o[b];d?c(!0):lb(a.c,b,function(e){e?
(d=new tb(b,a.a,a.c),a.o[b]=d,d.D=e.user,d.K=e.session,c(!0)):Ta(a.C,b,function(d){d&&d.valid?(d=new tb(b,a.a,a.c),a.o[b]=d,kb(a.c,b,d,H(a.j),function(){c(!0)})):c(!1)})})},Ab=function(a,b){B()||wa()||xa()?a.pa.push(b):ta(va()?document:window,"storage",b)},U=function(a,b,c){this.b=a;this.a=new db(a,b);this.j=new Na(E.ga,E.Pa);this.C=new Ra(a,c);this.c=new jb(a,this.j);this.F=new wb(this.j,this.a,this.C,this.c)};h=U.prototype;
h.start=function(){var a=this,b=function(){a.a.Ab.apply(a.a,arguments)},c=function(){T(a.a,{type:"idpReady"});x("Initialize IDP IFrame successfully.")},d=function(c){var d=window;if(d.removeEventListener)d.removeEventListener("message",b,!1);else if(d.detachEvent)d.detachEvent("onmessage",b);else throw"Remove event handler for message failed.";Oa(a.j);T(a.a,{type:"idpError",error:c.message})};try{fb(this.a,this.Da()),ta(window,"message",b),Ab(this.F,hb(this.a)),Ab(this.F,ib(this.a)),Qa(this.j),u.rb(c,
d)}catch(e){d(e)}};h.wb=function(a){var b=this;zb(this.F,(a.params||{}).clientId,function(c){S(b.a,a.id,c)})};
h.ib=function(a){var b=a.params||{},c=this,d=function(b){S(c.a,a.id,b)},e=b.clientId,g=b.loginHint,f=b.request,n=b.sessionSelector;f.client_id=e;f.login_hint=g;f.ss_domain=n.domain;var m=H(this.j);if(m){var v=function(a){a&&!a.error&&a.login_hint?(a.first_issued_at=(new Date).getTime(),a.expires_at=a.first_issued_at+1E3*a.expires_in,a.session_state||(a.session_state={}),a.scope||(a.scope=f.scope),b.skipCache?yb(c.F,e,a,m,function(){d(a)}):nb(c.c,m,e,f.response_type,a,b.id,function(){yb(c.F,e,a,m,
function(){d(a)})})):(a=a||{},d(a))};b.forceRefresh?Wa(this.C,f,v):mb(this.c,g,e,f.response_type,f.scope,b.id,function(a){a&&18E4<a.expires_at-(new Date).getTime()?yb(c.F,e,a,m,function(){d(a)}):Wa(c.C,f,v)})}else S(c.a,a.id,{error:"user_logged_out"})};h.lb=function(a){var b=this,c=function(c){S(b.a,a.id,c)};if(H(this.j)){var d=a.params||{},e=d.request,g=d.sessionSelector;e.client_id=d.clientId;e.login_hint=d.loginHint;e.ss_domain=g.domain;Xa(this.C,e,c)}else c({error:"user_logged_out"})};
h.Cb=function(a){var b=a.params||{},c=b.clientId,d=this;Za(this.C,b.token,function(b){ob(d.c,c,function(){S(d.a,a.id,b)})})};h.Jb=function(a){if(B()||wa()||xa()){var b=a.params||{},c=(new O).f({clientId:b.clientId,id:b.id,origin:b.origin});b=this.F;if(B()||wa()||xa()){b.U&&b.U.stop();b.U=new F(c);for(c=0;c<b.pa.length;c++)b.U.addListener(b.pa[c]);b.U.start()}}S(this.a,a.id,!0)};h.hb=function(a){var b=this,c=a.params||{};pb(this.c,c.domain,c.crossSubDomains,c.id,c.policy,function(c){S(b.a,a.id,c)})};
h.Hb=function(a){var b=a.params||{},c=b.hint,d=!!b.disabled,e=b.domain,g=b.crossSubDomains,f=b.id,n=b.policy,m=this;if(c||d)var v={hint:c,disabled:d};qb(this.c,e,g,v,f,n,function(){T(m.a,{type:"sessionSelectorChanged",newValue:v,domain:e,crossSubDomains:g,id:f,policy:n});S(m.a,a.id,!0)})};
h.tb=function(a){var b=a.params||{},c=this,d=function(b){S(c.a,a.id,b)},e=b.clientId,g=b.request,f=b.sessionSelector;g.client_id=e;g.response_type="id_token";g.ss_domain=f.domain;var n=H(this.j);if(n){var m=function(a){a&&!a.error?(a.first_issued_at=(new Date).getTime(),a.expires_at=a.first_issued_at+1E3*a.expires_in,a.scope=g.scope,sb(c.c,n,e,a,function(){d(a)})):(a=a||{error:"No response returned from Server."},d(a))};b.forceRefresh?Ya(this.C,g,m):rb(this.c,e,g.scope,function(a){a?d(a):Ya(c.C,g,
m)})}else d({scope:g.scope,sessions:[]})};h.xb=function(a){a=a&&a.params||{};return a.clientId&&!G(a.clientId)};h.qb=function(a){var b=a&&a.params||{};a=b.loginHint;var c=!G(b.id),d=b.clientId&&!G(b.clientId),e=!!b.request,g=e&&b.request.scope;(b=(e=e&&b.request.response_type)&&0<=b.request.response_type.indexOf("code"))&&x("Bad request: 'code' response_type is not supported.");return a&&c&&d&&g&&e&&!b};
h.mb=function(a){a=a&&a.params||{};var b=!G(a.id),c=a.clientId&&!G(a.clientId),d=!!a.request&&a.request.scope;return a.loginHint&&b&&c&&d};h.ob=function(a){a=a&&a.params||{};var b=a.domain&&!G(a.domain),c=!G(a.policy);return!G(a.id)&&b&&c&&this.c.s(a.domain,!!a.crossSubDomains,a.policy)};h.Ib=function(a){a=a&&a.params||{};var b=a.domain&&!G(a.domain),c=!G(a.policy);return!G(a.id)&&b&&c&&this.c.s(a.domain,!!a.crossSubDomains,a.policy)&&E.Xa(a)};
h.ub=function(a){a=a&&a.params||{};var b=a.clientId&&!G(a.clientId),c=!!a.request&&a.request.scope;return!G(a.id)&&b&&c};h.Db=function(a){a=a&&a.params||{};var b=!!a.token,c=a.clientId&&!G(a.clientId);return!G(a.id)&&b&&c};h.Kb=function(a){a=a&&a.params||{};var b=a.origin&&!G(a.origin),c=a.id&&!G(a.id);return a.clientId&&!G(a.clientId)&&b&&c};h.Fb=function(a){var b;if(b=a.clientId)a=a.clientId,b=!(!a||!this.F.o[a]);return b};
h.Ya=function(a){var b;if(b=a.clientId)b=a.clientId,b=!(!b||!this.F.o[b]);return b&&a.id&&a.authResult};h.Eb=function(a){return a.domain&&this.c.s(a.domain,a.crossSubDomains,a.policy)};var V=function(a,b){return function(){return b.apply(a,arguments)}};U.prototype.Da=function(){var a={u:[],G:[]};Bb(this,a);return a};
var Bb=function(a,b){b.u.push({method:"monitorClient",v:V(a,a.wb),I:!1,B:V(a,a.xb)});b.u.push({method:"getTokenResponse",v:V(a,a.ib),I:!0,B:V(a,a.qb)});b.u.push({method:"getOnlineCode",v:V(a,a.lb),I:!0,B:V(a,a.mb)});b.u.push({method:"getSessionSelector",v:V(a,a.hb),I:!0,B:V(a,a.ob)});b.u.push({method:"setSessionSelector",v:V(a,a.Hb),I:!1,B:V(a,a.Ib)});b.u.push({method:"listIdpSessions",v:V(a,a.tb),I:!0,B:V(a,a.ub)});b.u.push({method:"revoke",v:V(a,a.Cb),B:V(a,a.Db)});b.u.push({method:"startPolling",
v:V(a,a.Jb),B:V(a,a.Kb)});b.G.push({type:"idpReady"});b.G.push({type:"idpError"});b.G.push({type:"sessionStateChanged",filter:V(a,a.Fb)});b.G.push({type:"sessionSelectorChanged",filter:V(a,a.Eb)});b.G.push({type:"authResult",filter:V(a,a.Ya)})};var Cb="client_id origin ss_domain scope privileged authuser".split(" ");var Fb=function(a,b,c){b.origin=a.b;b.privileged=!0;b=Va(b,Cb);I(E.fa,b,Eb(a.b),function(a){c(a)})};
function Eb(a){var b={},c=D.J(E.nb());if(c){if(!c)throw Error("Session cookie value cannot be empty.");c=new r(new t,ma(c));a=ma(a);c.reset();c.update(a);a=c.digest();c=ia(a);la("array"==c||"object"==c&&"number"==typeof a.length,"encodeByteArray takes an array as a parameter");if(!q)for(q={},c=0;65>c;c++)q[c]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c);c=q;for(var d=[],e=0;e<a.length;e+=3){var g=a[e],f=e+1<a.length,n=f?a[e+1]:0,m=e+2<a.length,v=m?a[e+2]:0,Db=g>>2;
g=(g&3)<<4|n>>4;n=(n&15)<<2|v>>6;v&=63;m||(v=64,f||(n=64));d.push(c[Db],c[g],c[n],c[v])}b["X-Csrf-Token"]=d.join("")}return b};var W=function(){};z(W,M);W.prototype.f=function(a){a=void 0===a?{}:a;return["gsi_gs",void 0===a.origin?null:a.origin,void 0===a.clientId?null:a.clientId].join(E.g)};W.prototype.l=function(a,b,c){var d=this;c=void 0===c?function(){}:c;M.prototype.l.call(this,a,b,function(b){b?!b.expires_at||b.expires_at<=(new Date).getTime()?L(d).removeItem(d.f(a),function(){return c(null)}):(b.expires_at=void 0,c(b)):c(null)})};
W.prototype.m=function(a,b,c,d){b&&(b.expires_at=(new Date).getTime()+864E5);M.prototype.m.call(this,a,b,c,d)};U.prototype.fb=function(a){var b=this;a=void 0===a?{}:a;var c=a.id,d=void 0===a.params?{}:a.params,e=function(a){a&&a.sessions?(a=Gb(g,a.sessions),S(b.a,c,a)):S(b.a,c,null)},g=d.loginHint;delete d.loginHint;var f=H(this.j);if(f){a=d.clientId;var n=d.request;d=d.sessionSelector;n.client_id=a;n.ss_domain=d.domain;var m=new W,v={clientId:a,origin:this.b};m.l(v,f,function(a){a?e(a):Fb(b.C,n,function(a){!a||a.error?e(null):m.m(v,a,f,function(){e(a)})})})}else e(null)};
function Gb(a,b){if(!b.length)return null;var c=a.toLowerCase();b=ha(b);for(var d=b.next();!d.done;d=b.next())if(d=d.value,d.login_hint){if(a===d.obfuscatedGaiaId)return d.login_hint;if(d.emails&&d.emails.length)for(var e=ha(d.emails),g=e.next();!g.done;g=e.next())if(c===g.value.toLowerCase())return d.login_hint}return null};U.prototype.gb=function(a){a=void 0===a?{}:a;a=void 0===a.params?{}:a.params;var b=!!a.clientId&&!G(a.clientId),c=!!a.request,d=!!a.sessionSelector;return!!a.loginHint&&b&&c&&d};U.prototype.Da=function(){var a={u:[],G:[]};Bb(this,a);a.u.push({method:"gsi:fetchLoginHint",v:V(this,this.fb),I:!0,B:V(this,this.gb)});return a};E.ga="APISID";E.ya="SAPISID";E.Aa="/o/oauth2/iframerpc?action=sessionState";E.ta="/o/oauth2/iframerpc?action=checkOrigin";E.xa="/o/oauth2/iframerpc?action=issueToken";E.wa="/o/oauth2/iframerpc?action=issueOnlineCode";E.fa="/o/oauth2/iframerpc?action=listSessions";
var Hb=function(){var a=sa("origin");if(!a)throw"Failed to get parent origin from URL hash!";var b=sa("rpcToken");if(!b)throw"Failed to get rpcToken from URL hash!";var c=sa("debug");pa="0"!=c&&!!c;(new U(a,b)).start()},X=["lso","startIdpIFrame"],Y=this;X[0]in Y||!Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===Hb?Y=Y[Z]&&Y[Z]!==Object.prototype[Z]?Y[Z]:Y[Z]={}:Y[Z]=Hb;
